image:
  file: .gitpod.dockerfile
tasks:
  - before: sudo mount -t tmpfs shm -osize=4096m /dev/shm
  - init: |
      flutter config --enable-web
      flutter doctor
      flutter pub get
      flutter build -v web
      
  - command: |
      flutter pub get


ports:
  - port: 5900
    onOpen: ignore
    # vnc
  - port: 6080
    onOpen: open-preview
    # flutter
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - dart-code.flutter
