image:
  file: .gitpod.dockerfile
tasks:
  - init: |
      flutter channel beta
      flutter upgrade

      flutter config --enable-web
      flutter config --android-sdk /home/gitpod/androidsdk
      yes | flutter doctor --android-licenses

      flutter doctor

      flutter pub get

      flutter build -v web
      
  - command: |
      flutter devices
    
      flutter run --web-port 8080


ports:
  - port: 5900
    onOpen: ignore
    # vnc
  - port: 6080
    onOpen: open-preview
    # flutter
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - dart-code.flutter
