name: Build

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rm lib/repositories/repository.dart
    - run: mv lib/repositories/repository.prod lib/repositories/repository.dart
    
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    
    - name: Android
      run: flutter build apk
    
    - uses: actions/upload-artifact@master
      name: Upload apk
      with:
        name: apk
        path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: rm lib/repositories/repository.dart
    - run: mv lib/repositories/repository.prod lib/repositories/repository.dart

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    
    - uses: actions/upload-artifact@master
      name: Upload ios
      with:
        name: ios
        path: build/ios/iphoneos/Runner.app
