name: Codecov

on:
  push:
    branches: [ dev ]

jobs:
  upload_lcov:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: sudo apt-get -y install libsqlite3-0 libsqlite3-dev
      - run: flutter pub get
      - run: flutter test --coverage
      - uses: codecov/codecov-action@v3
        with:
          file: coverage/lcov.info
