name: Codecov

on:
  push:
    branches: [ dev ]
  workflow_run:
    workflows: [Test]
    branches: [dev]
    types:
      - completed

jobs:
  upload_lcov:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.0.2'
      - run: sudo apt-get -y install libsqlite3-0 libsqlite3-dev
      - run: flutter pub get
      - run: flutter test --coverage
      - uses: codecov/codecov-action@v3
        with:
          file: coverage/lcov.info
