name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jacopocarlini/action-autotag@2.0.4
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
