name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.0.2'
      - run: sudo apt-get -y install libsqlite3-0 libsqlite3-dev
      - run: flutter pub get
      - run: flutter test
